[package]
name = "fastcdc"
version = "1.0.7"
authors = ["Nathan Fiedler <nathanfiedler@fastmail.fm>"]
edition = "2018"
description = "FastCDC (content defined chunking) in pure Rust."
repository = "https://github.com/nlfiedler/fastcdc-rs"
readme = "README.md"
keywords = ["cdc", "chunking"]
license = "MIT"
exclude = [
    "TODO.org",
    "test/*",
]

[dev-dependencies]
memmap = "0.7.0"
crypto-hash = "0.3.4"
clap = { version = "4.0.32", features = ["cargo"] }
