[package]
name = "fastcdc"
version = "2.0.0"
authors = ["Nathan Fiedler <nathanfiedler@fastmail.fm>"]
edition = "2018"
description = "FastCDC (content defined chunking) in pure Rust."
repository = "https://github.com/nlfiedler/fastcdc-rs"
readme = "README.md"
keywords = ["cdc", "chunking"]
license = "MIT"
exclude = [
    "TODO.org",
    "test/*",
]

[dev-dependencies]
aes = "0.8.2"
byteorder = "1.4.3"
clap = { version = "4.1.4", features = ["cargo"] }
ctr = "0.9.2"
md-5 = "0.10.5"
memmap2 = "0.5.8"
